### PR TITLE
add romanian translation

### PR DESCRIPTION
**Pull request by tudorbarascu**
Hello. Is there anywhere else that I need to do something?

Thanks for this very nice project.

### CODE REVIEW

**Comment by volterra79** [comment]
@tudorbarascu Thanks. I added romanian translation

**Comment by volterra79** [comment]
@tudorbarascu Can you help me to translate also 3 main core plugins in romanian?
https://github.com/g3w-suite/g3w-client-plugin-editing
https://github.com/g3w-suite/g3w-client-plugin-qplotly
https://github.com/g3w-suite/g3w-client-plugin-qtimeseries

You can find i18n  transaltion insied config folder.

Thanks

**Comment by tudorbarascu** [comment]
@volterra79 Will do ASAP, thank you!

**Comment by volterra79** [comment]
@tudorbarascu thanks

**Comment by wlorenzetti** [comment]
@tudorbarascu I would not like to take advantage of your kindness too much but if you want and can you can also do the translation for the administration part? :)

**Comment by tudorbarascu** [comment]
@wlorenzetti Will do, trying to figure out right now where to do that for the admin. It seems I couldn't manage. Is there a tutorial on how to do it? Thanks

**Comment by wlorenzetti** [comment]
@tudorbarascu thanks a lot! I'll prepare files for the Romanian language, I think you jus known how translation work in Django, I'll make the *.po files.

**Comment by wlorenzetti** [comment]
@tudorbarascu I just added Romanian language files to g3w-admin, when you can, thanks in advance :). https://github.com/g3w-suite/g3w-admin/commit/76969c567a08929929748cb7e122fc9726a3d935

**Pull request merged**
