### PR TITLE
Refactor guplfile.js

### PR DESCRIPTION
**Pull request by Raruto**
First rewrite of the gulpfile to try to make it easier for anyone to understand:

- move declare statements to top
- avoid some negative conditionals
- comment out dead code
- use multiline comments for tasks
- inline some unnecessary functions definitions

Related to: https://github.com/g3w-suite/g3w-client/pull/29

### CODE REVIEW

**Comment by volterra79** [comment]
@Raruto done. I checked and i need to push a commit to fix an issue on gulpfile regarding 'browser-sync' task on line 322:
const port = conf.localServerPort ?? 3000; to const port = conf.localServerPort || 3000;

**Comment by Raruto** [comment]
@volterra79 

ok, but keep in mind that the following statement:

```js
const port = conf.localServerPort ?? 3000;
```

is equivalent to the following (which was the starting code):

```js
const port = conf.localServerPort ? conf.localServerPort : 3000;
```

and not to:

```js
const port = conf.localServerPort || 3000;
```

_or at least I think so_

**Comment by volterra79** [comment]
@Raruto you are right. If run **npm run default** using 
```js
const port = conf.localServerPort ?? 3000; 
```
i receive an error

`const port = conf.localServerPort ?? 3000;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
`

**Comment by Raruto** [comment]
yes, there is probably a project dependency with does not yet support the nullish coalescing operator.

**Comment by volterra79** [comment]
@Raruto i investigate on it

**Pull request merged**
