### PR TITLE
Prevent tooltips help text from being occasionally clipped by surrounding containers (ref: mouse over hints)

### LINKED ISSUE #362: Tooltip text gets cropped by surrounding container
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Some unfortunate circumstances can lead to [boostrap's tooltip](https://getbootstrap.com/docs/3.3/javascript/#tooltips) being clipped.

Here are some of the cases I've encountered, I don't know if there can be even worse ones (and if with the current bootstrap version it can be solved somehow or easily..):

### Sidebar results panel: "Add/Remove features to results"
image

### Map controls: "Geo Screenshot"

image

### Steps to reproduce

1. click on any map overlay to open the sidebar
2. resize the sidebar results panel to `width: 264.16px` (as above image)
3. move the mouse over various elements to see if their tooltips are clipped

### Environment

- g3w-admin: __3.5.dev-20230224161958__
- g3w-client: __3.8.0-alpha.1__
- browser: __Firefox and Chrome 110__
- operating system: __Windows 10 (64 bit)__

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #362 

## Before

image

image

## After

image

image

### CODE REVIEW

**Comment by Raruto** [comment]
1. double check css selectors

Recording 2023-03-03 at 12 23 17

2. evaluate whether to use another color for the background of the bootstrap tooltip (the black color above the map controls is easier to read)

**Comment by Raruto** [comment]
1. it seems to me that there are some map controls (e.g. zoom-in, zoom-out, fit-to-extent, ..) that still use the old tooltip data attribute (i.e. not attached to the `<body>`)
2. in the new version fonts and spacings are smaller (the bubble direction arrow has also appeared).

Recording 2023-03-03 at 15 37 43

**Comment by volterra79** [comment]
> 1. it seems to me that there are some map controls (e.g. zoom-in, zoom-out, fit-to-extent, ..) that still use the old tooltip data attribute (i.e. not attached to the `<body>`)
> 2. in the new version fonts and spacings are smaller (the bubble direction arrow has also appeared).
> 
> Recording 2023-03-03 at 15 37 43 

@Raruto i can't replicate it. I'll let you know

**Review by Raruto — CHANGES_REQUESTED** [review]
@volterra79 please, resolve merge conflicts

**Review by Raruto — APPROVED** [review]
@volterra79 In here https://github.com/g3w-suite/g3w-client/pull/363/commits/eb54a1540fe4d60c8bb3adf7e3b39a3de5442e50 I also set a black background for all tooltips.

That's why using the primary color will most of the time make it difficult to spot/read, here's an example:

## Before

image

## After

image

**Comment by volterra79** [comment]
@Raruto it could be better show tooltip with class skin-background-color instead black

**Review by Raruto — APPROVED** [review]

**Pull request merged**
