### PR TITLE
Add new geocoding provider: Bing (Locations API)

### LINKED ISSUE #498: Bings Maps geocoding control
### Checklist

- [x] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

As per 2020's [Google Maps Terms](https://cloud.google.com/maps-platform/terms),

it is no longer allowed to use google maps in custom applications (eg. [Open Layers](https://openlayers.org/))

> (e) No Use With Non-Google Maps. To avoid quality issues and/or brand confusion, Customer will not use the Google Maps Core Services with or near a non-Google Map in a Customer Application. For example, Customer will not (i) display or use Places content on a non-Google map, (ii) display Street View imagery and non-Google maps on the same screen, or (iii) link a Google Map to non-Google Maps content or a non-Google map.

### Suggested solution

1. Deprecate Google Geocoding provider (ref: [#131](https://github.com/g3w-suite/g3w-client/pull/131))
2. Add support to [Bing Locations API](https://learn.microsoft.com/en-us/bingmaps/rest-services/locations/)
3. Allow the end user to inspect the resulting geocoded markers (similar to [bing.com/maps](https://www.bing.com/maps/) search results)

image

image

### Bing Maps

- https://openlayers.org/en/latest/examples/bing-maps.html
- https://www.microsoft.com/en-us/maps/bing-maps/product

> Section 4. Use of the Services.
>
> (g) You may use geocodes with third-party maps.
>
> Section 5. General Restrictions.
>
> (g) Use of the Content may not be used in combination with any open source software or other data subject to an open source license that may impair the copyright protection of the Content.
>
> (k) Redistribute, resell, or sublicense access to any Microsoft service or Content;
>
> (m) Circumvent or bypass transaction limits by any means or in any manner, including by creating multiple accounts;
>
> (r) Integrate road maps from the Services with third-party roadmaps;
>
> (s) Display any Service results, except geocodes, on third-party maps;
>
> (t) Replace imagery from the Services with imagery supplied by any other mapping platform. Notwithstanding the foregoing, you may overlay aerial imagery that you have the rights to use, provided that such imagery does not substantially replace the base aerial imagery provided by the Services. You may incorporate various data layers of types not available through the Services, in the Applications (for example, demographic or school location data); or

### Arcgis

- https://developers.arcgis.com/openlayers/faq/
- https://developers.arcgis.com/openlayers/geocode-and-search/

> **Is OpenLayers a supported API?**
>
> Yes, OpenLayers is a supported API that you can use to build applications with ArcGIS location services.
>
> **Which ArcGIS services can I access with OpenLayers?**
>
> You can access other services such as the geocoding service, routing service, and GeoEnrichment service by using ArcGIS REST JS.
>
> **What type of account do I need to access ArcGIS location services?**
>
> You need either an ArcGIS Developer account or ArcGIS Online account. This will give you the ability to access the developer dashboard, create API keys, set up OAuth 2.0, and manage your data.

### PR DESCRIPTION
**Pull request by Raruto**
## Depends on:

- https://github.com/g3w-suite/g3w-admin/pull/646
- https://github.com/g3w-suite/g3w-client-plugin-editing/pull/72

## Premise

1. As per 2023/10 [Bing Local Search API](https://learn.microsoft.com/en-us/bingmaps/rest-services/locations/local-search) supports searches for business entities **only in the USA**.
2. Dynamic field mapping is currently not supperted while saving geocoding results into a project layer (ie. target layers must have the same field names as the resulting geocoding fields to work correctly, see: [available bing attributes](https://user-images.githubusercontent.com/9614886/281331436-bef5cd4c-05bf-4c23-950b-3d46d6c432bc.png) and [sample target editable layer](https://github.com/g3w-suite/g3w-client/assets/9614886/d0e46b82-9a2b-43c9-81ad-1437f859f559)).
3. autogenerated fields (which do not collide with each other) are also mappable without using the provider prefix (and using lower case notation), eg:
   - `bing_Website` → `website`
   - `bing_Address_postalCode` → `address_postalcode`
   - `bing_Address_locality` → `address_locality`

## Docker settings

```py
# config/g3w-suite/settings_docker.py

VENDOR_KEYS = {
 'bing': 'your.super.secret.key'
}

GEOCODING_PROVIDERS = {
  "nominatim": {
    "label": "Nominatim (OSM)",
    "url": "https://nominatim.openstreetmap.org/search",
    # "icon": "road",
  },
  "bing_streets": {
    "label": "Bing Streets",
    "url": "https://dev.virtualearth.net/REST/v1/Locations/?key=" + VENDOR_KEYS['bing'], # + '&inclnb=1',
    # "icon": "road",
  },
  "bing_places": {
    "label": "Bing Places",
    "url": "https://dev.virtualearth.net/REST/v1/LocalSearch/?key=" + VENDOR_KEYS['bing'],
    # "icon": "poi",
  },
}
```

To set a vendor key you can do as is most comfortable for you, e.g.:

- `?key=" + VENDOR_KEYS['bing']` ← passing it directly into the url
- `VENDOR_KEYS['bing'] = "super.secret.key"` ← setting a generic global key
- `VENDOR_KEYS['bing_search'] = "super.secret.key"` ← setting a specific key to that service

If you would like to add new providers (or rename existing ones), just remember to use the file name as "provider" identifier:

```
http://localhost:8000/static/client/geocoding-providers/bing_streets.js
http://localhost:8000/static/client/geocoding-providers/bing_places.js
http://localhost:8000/static/client/geocoding-providers/nominatim.js
http://localhost:8000/static/client/geocoding-providers/my_custom_provider.js
...
```

```py
# config/g3w-suite/settings_docker.py

GEOCODING_PROVIDERS = {
  "bing_streets": { ... },
  "bing_places":  { ... },
  "nominatim":    { ... },
  "my_custom_provider": {
    "label": "Custom Provider",
    "url": "https://example.com/search"
  },
}

VENDOR_KEYS['my_custom_provider'] = 'super.secret.key' 
```

## How to test

1. download [demo-geocoding.zip](https://github.com/g3w-suite/g3w-client/files/13265552/demo-geocoding.zip) and create a new project within g3w-admin
2. set all point layers as editable
5. perform a geocoding search (eg. `cafe`)

image

## Add new feature from geocoding results (bing or nominatim)

image

image

## Available attributes (bing)

image

## Available attributes (nominatim)

image

## Sample QGIS layer (target editable point layer)

image

Closes: https://github.com/g3w-suite/g3w-client/issues/498

### CODE REVIEW

**Comment by Raruto** [comment]
@volterra79 

## Before

image


## After

image

**Comment by Raruto** [comment]
tested with: [g3w-suite-demo-projects/projects/geocoding-control.qgs](https://github.com/g3w-suite/g3w-suite-demo-projects/commit/7515e3493b000b2a1508b52ec26a390e5ae12e4d)

**Comment by leolami** [comment]
I tested the functionality on this project

[https://dev.g3wsuite.it/it/map/iim/qdjango/234/
](https://dev.g3wsuite.it/it/map/iim/qdjango/234/)
user: galt
pwd: Galt123!!

Two observations:

- I don't see the icon on Bing results
- I don't see the icon on the map of the "places" added, whether they are from OSM or Bing

image

**Comment by volterra79** [comment]
@leolami I need to push missing icon on g3w-admin client static folder

**Review by Raruto — COMMENTED** [review]
@wlorenzetti @volterra79 you can update your docker settings as follows to test:

```py
# config/g3w-suite/settings_docker.py

VENDOR_KEYS = {
 'bing': 'your.super.secret.key'
}

GEOCODING_PROVIDERS = {
  "nominatim": {
    "label": "Nominatim (OSM)",
    "url": "https://nominatim.openstreetmap.org/search",
    # "icon": "road",
  },
  "bing_streets": {
    "label": "Bing Streets",
    "url": "https://dev.virtualearth.net/REST/v1/Locations/?key=" + VENDOR_KEYS['bing'], # + '&inclnb=1',
    # "icon": "road",
  },
  "bing_places": {
    "label": "Bing Places",
    "url": "https://dev.virtualearth.net/REST/v1/LocalSearch/?key=" + VENDOR_KEYS['bing'],
    # "icon": "poi",
  },
}
```

To set a vendor key you can do as is most comfortable for you, e.g.:

- `?key=" + VENDOR_KEYS['bing']` ← passing it directly into the url
- `VENDOR_KEYS['bing'] = "super.secret.key"` ← setting a generic global key
- `VENDOR_KEYS['bing_search'] = "super.secret.key"` ← setting a specific key to that service

If you would like to add new providers (or rename existing ones), just remember to use the file name as "provider" identifier:

```
http://localhost:8000/static/client/geocoding-providers/bing_streets.js
http://localhost:8000/static/client/geocoding-providers/bing_places.js
http://localhost:8000/static/client/geocoding-providers/nominatim.js
http://localhost:8000/static/client/geocoding-providers/my_custom_provider.js
...
```

```py
# config/g3w-suite/settings_docker.py

GEOCODING_PROVIDERS = {
  "bing_streets": { ... },
  "bing_places":  { ... },
  "nominatim":    { ... },
  "my_custom_provider": {
    "label": "Custom Provider",
    "url": "https://example.com/search"
  },
}

VENDOR_KEYS['my_custom_provider'] = 'super.secret.key' 
```

**Review by volterra79 — APPROVED** [review]

**Pull request merged**
