### PR TITLE
WMS service with GetMap URL different from GetCapabilitites URL fail

### PR DESCRIPTION
**Pull request by volterra79**
Referred to https://github.com/g3w-suite/g3w-admin/issues/600

### CODE REVIEW

**Comment by Raruto** [comment]
@volterra79 is this superseded by: https://github.com/g3w-suite/g3w-client/pull/512 ?

**Comment by volterra79** [comment]
> @volterra79 is this superseded by: #512 ?

@Raruto is another issue. We need to wait g3w-admin because there is a qgis-server bug.

**Comment by Raruto** [comment]
> is another issue.

ok, but both are referring to the same issue: https://github.com/g3w-suite/g3w-admin/pull/601 🤷

**Comment by volterra79** [comment]
> > is another issue.
> 
> ok, but both are referring to the same issue: [g3w-suite/g3w-admin#601](https://github.com/g3w-suite/g3w-admin/pull/601) 🤷

@Raruto you are right. G3w-admin PR is changed and refer to same issue. Please close it.

**Comment by Raruto** [comment]
Superseded by: https://github.com/g3w-suite/g3w-client/pull/512

**Pull request closed without merging**
