### PR TITLE
Add search support for `Relation Reference` widget (1:N relations)

### PR DESCRIPTION
**Pull request by volterra79**
## Depends on:

- https://github.com/g3w-suite/g3w-admin/pull/631
- https://github.com/g3w-suite/g3w-client-plugin-editing/pull/73

## Summary

Add support for **search** and **editing** capabilities on Relation Reference widget (1:N relations).

Ref: https://github.com/g3w-suite/g3w-admin/issues/616

## Before

image

## After

image

## G3W-ADMIN configuration

image

image

## QGIS configuration --> [16.1.9.2 Edit widgets > Relation Reference](https://docs.qgis.org/3.28/en/docs/user_manual/working_with_vector/vector_properties.html?highlight=relation%20widget#edit-widgets)

Screenshot from 2023-10-27 14-58-07

### CODE REVIEW

**Comment by Raruto** [comment]
@volterra79 links to the pdf files are gone (I didn't check on `dev` version).

## Before ([demo v3.6](https://v36.g3wsuite.it/en/map/demo-36/))

image


## After (localhost)

image

**Comment by volterra79** [comment]
@Raruto check value from server the document label field

Screenshot from 2023-11-09 12-26-25

**Comment by Raruto** [comment]
@volterra79 Maybe `mime_type` is null because the linked file doesn't exist anymore?

image

## API Request

```
http://localhost:8000/vector/api/editing/qdjango/1/maintenance_works_f8cbe34a_eebe_4cd1_9c78_5d420ab0af63/?relationonetomany=maintenanc_id_building_buildings__fid|7&formatter=0
```

## Problematic URL

https://v34.g3wsuite.it/en/me/qdjango/353/building_detection_card_CgiFkOC.pdf

**Comment by volterra79** [comment]
@Raruto Maybe. We nee to check from g3w-admin side.

Referred to image, link are not handle on relation table. We need to implement it in future release

**Comment by Raruto** [comment]
Same behavior when trying with current `dev` versions:

image

[g3wsdk.info]

- g3w-admin: __3.7.dev-20231109101139__
- g3w-client: __3.9.0-alpha.2.0__
- browser: __Firefox 119.0__
- operating system: __Windows 11 64-bit__

**Review by Raruto — APPROVED** [review]

**Pull request merged**
