### PR TITLE
Add search datetime input widget

### LINKED ISSUE #206: Add datetime search input field (search widgets)
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-client/issues) to make sure this feature hasn't been requested already.

### Motivation

In case of field datetime type of a layer, it could be useful to has a datetime widget for search panel instead a simple text input widget.

### Suggested solution

Create a search widget input component using https://getdatepicker.com/4/
How it works now:

Screenshot from 2022-09-22 15-22-08

How would like to work:

Screenshot from 2022-09-22 15-23-54

### Alternatives considered

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #206 
Add  `SearchDatetime.vue` component that is show in `SearchPanel.vue` if search input type is `'datetime'`

### CODE REVIEW

**Comment by Raruto** [comment]
@volterra79 could you also attach some details on how we can test it? (e.g. photos, a sample .qgs file, ...)

**Comment by volterra79** [comment]
@Raruto 

1. Need to [ create a search widget from g3w-admin](https://g3w-suite.readthedocs.io/it/latest/g3wsuite_administration.html?highlight=search#widget-setting-search-tools) using a date field of layer 
(green circle is the date type filed) (red circle is widget type Datetimebox for datetimefield)

Screenshot from 2022-09-30 12-08-49

**Comment by Raruto** [comment]
Are there any minimum requirements regarding **g3w-admin** and **qgis** versions to make this work?

**Comment by volterra79** [comment]
@Raruto it works with g3w-admin branch dev. Qgis version is not mandatory

**Comment by Raruto** [comment]
>  it works with g3w-admin branch dev. Qgis version is not mandatory

I am testing this with **g3w-admin@3.5.dev-20220930075850** and I am not able to get showed the "datetimefield" widget.

As for adding the `date` field to my project, I am using **QGIS v3.26.0-Buenos Aires**

Could you also attach a working example qgis project? (so i see if i'm wrong something in setting mine..)

**Comment by leolami** [comment]
Hi @Raruto 

here a web service with a date search

https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/201/

and here the QGIS project and data

[G3WSUITE_date.zip](https://github.com/g3w-suite/g3w-client/files/9685548/G3WSUITE_date.zip)

**Comment by volterra79** [comment]
@Raruto  in my previous [comment](https://github.com/g3w-suite/g3w-client/pull/207#issuecomment-1263381344) i make a mistake. To enable search datimebox search widget on a layer field, you need to set Date/Time widget on Qgis project as below:

Screenshot from 2022-10-05 11-04-44

After on g3w-admin admin, you cha choose datetimebox widget for layer field.

Screenshot from 2022-10-05 11-06-06

**Pull request merged**
