### PR TITLE
Porting qtimeseries plugin to client core

### PR DESCRIPTION
**Pull request by volterra79**
Porting https://github.com/g3w-suite/g3w-client-plugin-qtimeseries into client core

Screenshot from 2022-11-15 18-11-07

### CODE REVIEW

**Comment by Raruto** [comment]
For the moment I would wait a little longer before continuing in this direction.

Also in relation to this milestone objectives [v3.9](https://github.com/g3w-suite/g3w-client/milestone/9):

> Move client plugins:
>
> - [g3w-client-plugin-editing](https://github.com/g3w-suite/g3w-client-plugin-editing)
> - [g3w-client-plugin-qplotly](https://github.com/g3w-suite/g3w-client-plugin-qplotly)
> - [g3w-client-plugin-qtimeseries](https://github.com/g3w-suite/g3w-client-plugin-qtimeseries)
> 
> into core g3w-client repository

Because:

- when you merge everything into a single repository, you easily risk making your code more intricate and bulky
- when it comes to writing and testing (at all levels), it becomes even more difficult to understand which portion you are actually testing (the test folder will be even more sizeable if you merge everything into one place)
- those repositories are currently the only ones able to show anyone how to develop a third-party plugin (or start contributing to it more easily).

I know that sometimes it's a bit tedious to develop on multiple repositories, but keep in mind that a project that is too big and "customized" (ie. that doesn't faithfully follow the current "mainsteam" development rules) is very difficult to understand for newcomers...

**Comment by volterra79** [comment]
> 

@Raruto you can archive it as draft

**Comment by Raruto** [comment]
@volterra79 do you think that temporarily, it might make sense to include them as [gitmodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) inside the `src/plugins` folder? (as was the case for some g3w-admin extensions in the past https://github.com/g3w-suite/g3w-admin/issues/368)

In this way I think it would be enough to edit the `config.template.js` file to ensure that these plugins are always included into the generated bundle:

https://github.com/g3w-suite/g3w-client/blob/9be883adc82a56dbaa647bb1818d6051b6d21133/config.template.js#L8-L12

**Comment by volterra79** [comment]
@Raruto it think we can close it. It better to work with https://github.com/g3w-suite/g3w-client/pull/301

**Comment by Raruto** [comment]
> @Raruto it think we can close it. It better to work with #301

Bye #262 👋

**Pull request closed without merging**
