### PR TITLE
Remove deprecated files (from v3.6 / v.3.7) and replace them with related CJS to ESM imports

### LINKED ISSUE #177: Delete `src/app/gui/vue/utils.js`
As per **v3.6**, this is the only function inside that file:

https://github.com/g3w-suite/g3w-client/blob/6b490215635ebec99d1396ba7826154bb19fb7eb/src/app/gui/vue/utils.js#L1-L7

Check that it is no longer in use by other parties (eg. plugins) and then delete it permanently.

Related to: https://github.com/g3w-suite/g3w-client/issues/99

### PR DESCRIPTION
**Pull request by Raruto**
Permanently remove almost all files marked with a "deprecation notice" added during the **v3.6** / **v3.7** refactoring. Any changes made here should still be backward compatible with previous versions of g3w-client as they do not affect any published API.

## List of changes:

- Replaced by `src/app/constant.js`:
  - src/app/core/layers/filter/operators.js
  - src/app/gui/constraints.js
  - src/app/gui/print/printconfig.js
  - src/app/gui/search/constants.js

- Replaced by `src/mixins`:
  - src/app/gui/inputs/select/vue/selectmixin.js
  - src/app/gui/inputs/widgetmixins.js
  - src/app/gui/metadata/vue/components/metadatamixin.js

- Replaced by `src/app/core/utils/parsers`
  - src/app/core/parsers/parsers.js
  - src/app/core/parsers/response/parser.js
  - src/app/core/parsers/table/parser.js
  - src/app/core/parsers/vector/parser.js

- Replaced by `src/app/core/utils/validators`
  - src/app/core/validators/inputs/checkbox.js
  - src/app/core/validators/inputs/datetimepicker.js
  - src/app/core/validators/inputs/float.js
  - src/app/core/validators/inputs/integer.js
  - src/app/core/validators/inputs/radio.js
  - src/app/core/validators/inputs/range.js
  - src/app/core/validators/inputs/validator.js
  - src/app/core/validators/inputs/validators.js
  - src/app/core/validators/layers/validator.js

- Moved into `src/services`:
  - src/app/core/apiservice.js
  - src/app/core/clipboardservice.js
  - src/app/core/data/expression/service.js
  - src/app/core/data/ows/service.js
  - src/app/core/data/proxy/service.js
  - src/app/core/data/query/service.js
  - src/app/core/data/search/service.js
  - src/app/core/data/routerservice.js
  - src/app/core/editing/changesmanager.js
  - src/app/core/history_router.js
  - src/app/core/iframe/services/app/service.js
  - src/app/core/iframe/services/plugins/editing/service.js
  - src/app/core/iframe/services/plugins/index.js
  - src/app/core/relations/relationsservice.js
  - src/app/core/router.js
  - src/app/core/task/service.js
  - src/app/core/workflow/workflowsstack.js
  - src/app/gui/gui.js
  - src/app/gui/querybuilder/service.js

- Moved into `src/store`:
  - src/app/core/applicationstate.js
  - src/app/core/catalog/cataloglayersstoresregistry.js
  - src/app/core/editing/sessionsregistry.js
  - src/app/core/map/maplayersstoresregistry.js
  - src/app/core/plugin/pluginsregistry.js
  - src/app/core/project/projectsregistry.js
  - src/app/gui/component/componentsregistry.js
  - src/app/gui/map/control/registry.js

- Permanently removed (splitted into multiple files as before they defined more than one component):
  - src/app/gui/floatbar/floatbar.js (`FloatbarService` + `FloatbarComponent`)
  - src/app/gui/inputs/baseinput/baseinput.js (`BaseInputComponent` + `BaseInputMixin`)
  - src/app/gui/navbar/navbaritems.js (`NavbarItemsService` + `NavbaritemsLeftComponent` + `NavbaritemsRightComponent`)
  - src/app/gui/sidebar/sidebar.js (`SidebarService` + `SidebarComponent`)
  - src/app/gui/viewport/viewport.js (`ViewportService` + `ViewportComponent`)

- Permanently removed (added to `.gitignore` for easy checkout to previous branches):
  - src/config/dev/index.js
  - src/config/keys/index.js
  - src/config/i18n/index.js
  - src/config/index.js
  - src/config/README.md

- Permanently removed:
  - src/app/gui/inputs/services.js (as it is only used within: `src\app\gui\inputs\input.js`)
  - src/app/gui/vue/utils.js (as no longer in use)
  - src/app/gui/vue/vue.mixins.js (replaced by `src/mixins`)

---

Close: https://github.com/g3w-suite/g3w-client/issues/177

### CODE REVIEW

**Comment by Raruto** [comment]
@volterra79 before you merge this, please give me a short summary of your changes so I can update the [pull description](https://github.com/g3w-suite/g3w-client/pull/252#issue-1434450594) with the final changes

**Comment by volterra79** [comment]
@Raruto sure

**Comment by volterra79** [comment]
@Raruto list of delete files:

src/app/core/apiservice.js
src/app/core/applicationstate.js
src/app/core/catalog/cataloglayersstoresregistry.js
src/app/core/clipboardservice.js
src/app/core/data/expression/service.js
src/app/core/data/ows/service.js
src/app/core/data/proxy/service.js
src/app/core/data/query/service.js
src/app/core/data/routerservice.js
src/app/core/data/search/service.js
src/app/core/editing/changesmanager.js
src/app/core/editing/sessionsregistry.js
src/app/core/history_router.js
src/app/core/iframe/services/app/service.js
src/app/core/iframe/services/plugins/editing/service.js
src/app/core/iframe/services/plugins/index.js
src/app/core/layers/filter/operators.js
src/app/core/map/maplayersstoresregistry.js
src/app/core/parsers/parsers.js
src/app/core/parsers/response/parser.js
src/app/core/parsers/table/parser.js
src/app/core/parsers/vector/parser.js
src/app/core/plugin/pluginsregistry.js
src/app/core/project/projectsregistry.js
src/app/core/relations/relationsservice.js
src/app/core/router.js
src/app/core/task/service.js
src/app/core/validators/inputs/checkbox.js
src/app/core/validators/inputs/datetimepicker.js
src/app/core/validators/inputs/float.js
src/app/core/validators/inputs/integer.js
src/app/core/validators/inputs/radio.js
src/app/core/validators/inputs/range.js
src/app/core/validators/inputs/validator.js
src/app/core/validators/inputs/validators.js
src/app/core/validators/layers/validator.js
src/app/core/workflow/workflowsstack.js
src/app/gui/component/componentsregistry.js
src/app/gui/constraints.js
src/app/gui/floatbar/floatbar.js
src/app/gui/gui.js
src/app/gui/inputs/baseinput/baseinput.js
src/app/gui/inputs/select/vue/selectmixin.js
src/app/gui/inputs/widgetmixins.js
src/app/gui/map/control/registry.js
src/app/gui/metadata/vue/components/metadatamixin.js
src/app/gui/navbar/navbaritems.js
src/app/gui/print/printconfig.js
src/app/gui/querybuilder/service.js
src/app/gui/search/constants.js
src/app/gui/sidebar/sidebar.js
src/app/gui/viewport/viewport.js
src/app/gui/vue/utils.js
src/app/gui/vue/vue.mixins.js
src/config/README.md
src/config/dev/index.js
src/config/i18n/index.js
src/config/index.js
src/config/keys/index.js

**Comment by Raruto** [comment]
@volterra79 Can you also check that there are no imports of that deleted files within the `tests` folder? (i.e. do the tests still works even after this pull?)

For example:

https://github.com/g3w-suite/g3w-client/blob/58887a828986cf9c055a3d189da062fdf56a0ba2/test/specs/application/group/project/searches/test.js#L2

**Comment by volterra79** [comment]
@Raruto i think that test folder will be removed. we need to think a new way of Test. 
Anyway i'll check and change all reference in test folder files to delete files. Thanks

**Pull request merged**
