### PR TITLE
Add `src/store` folder (registry singletons refactor)

### LINKED ISSUE #91: Consolidate application `registries` within a single folder
Create a **`src/store`** folder and move all the following files into it (there are probably others that do not conform with the "registry" suffix, for example: "stack", "store", "relation", "flow", "history", "queue", ...):

---

**src/app/core/**

---

- `catalog/cataloglayersstoresregistry.js`
- `editing/sessionsregistry.js`
- ~~`layers/layersstore.js`~~ (this is not a singleton!)
- ~~`layers/layersregistry.js`~~ (this is not a singleton!)
- `map/maplayersstoreregistry.js`
- ~~`map/mapsregistry.js`~~ (this is not a singleton!)
- `plugin/pluginsregistry.js`
- `project/projectsregistry.js`

---

**src/app/gui/**

---

- `component/componentsregistry.js`
- `map/control/registry.js`

### PR DESCRIPTION
**Pull request by Raruto**
Consolidate the following singletons definitions within a single folder:
  -  **`LayersStoresRegistry`**
  - **`ComponentsRegistry`**
  - **`ControlsRegistry`**
  - **`MapLayersStoresRegistry`**
  - **`PluginsRegistry`**
  - **`ProjectsRegistry`**
  - **`SessionsRegistry`** 

**List of changes:**

- create `src/store` folder
- deprecate notice for `core/catalog/cataloglayersstoresregistry.js`
- deprecate notice for `core/editing/sessionsregistryjs`
- deprecate notice for `core/map/maplayersstoresregistryjs`
- deprecate notice for `core/plugin/pluginsregistryjs`
- deprecate notice for `core/project/projectsregistryjs`
- deprecate notice for `gui/component/componentsregistryjs`
- deprecate notice for `gui/map/control/registryjs`

Closes: https://github.com/g3w-suite/g3w-client/issues/91

### CODE REVIEW

**Comment by Raruto** [comment]
Perhaps it would be better to use just the word `store` as folder name?

**Comment by volterra79** [comment]
@Raruto i think for now we can name folder src/registry instead of src/store. What do you think?

**Comment by Raruto** [comment]
The `store` folder should be more common within the vue ecosystem (and in the near future other files that contain an application state will also need to be rewritten to be moved here, eg: https://github.com/g3w-suite/g3w-client/pull/95).

**Comment by volterra79** [comment]
@Raruto ok. Move to store folder for now

**Review by volterra79 — APPROVED** [review]
Done

**Pull request merged**
