### PR TITLE
Fix not empty results for 1:N relations (search widget)

### LINKED ISSUE #514: Search with relation show all relation layer features when no result
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Show all relation layer features when search has no result on layer where is set the search

### Steps to reproduce

1. Create a search with relation

Screenshot from 2023-11-02 11-26-15

3. Do a search with no result of current search layer 

### Environment

- g3w-admin: v3.6.14
- g3w-client: v3.8.12
- browser: all

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #514 

## How to test

1. Create a search on 1:n relation

Screenshot from 2023-11-02 11-26-15

2. Do a search that return no feature (eg. search a `fid` that not exist)

Screenshot from 2023-11-02 11-28-02

## Before

Shows all relation layer feature results

Screenshot from 2023-11-02 11-33-31

## After:

No features

Screenshot from 2023-11-02 11-29-26

### CODE REVIEW

**Comment by Raruto** [comment]
@volterra79 I get the following on existing `fid`:

```
TypeError: referencingField.map is not a function
```

image

And then the results panel is not shown.

**Comment by volterra79** [comment]
> @volterra79 I get the following on existing `fid`:
> 
> ```
> TypeError: referencingField.map is not a function
> ```
> 
> image
> 
> And then the results panel is not shown.

@Raruto maybe you need to save again the project because relation fields are not array

**Comment by Raruto** [comment]
@volterra79 after saving again the project:

```
TypeError: value.split is not a function
```
image

**Comment by volterra79** [comment]
> @volterra79 after saving again the project:
> 
> ```
> TypeError: value.split is not a function
> ```
> 
> image

@Raruto please provide me the g3w-admin version

**Comment by Raruto** [comment]
[g3wsdk.info]

- g3w-admin: __3.6.dev-20231031093516__
- g3w-client: __3.9.0-alpha.2.0__
- browser: __Firefox 119.0__
- operating system: __Windows 10 64-bit__

**Review by Raruto — APPROVED** [review]

**Pull request merged**
