### PR TITLE
Add support for `g3w-admin-mapproxy` plugin (tiles cache provider)

### PR DESCRIPTION
**Pull request by volterra79**
Related to https://github.com/g3w-suite/g3w-admin-mapproxy

### CODE REVIEW

**Review by wlorenzetti — APPROVED** [review]

**Comment by Daparrag** [comment]
Hi Guys, 
I want to know if you can help me to understand how this plugging works and how can I use it. 
I want to integrate the mapproxy configuration file. However I'm not sure if this is possible with g3wsuite. 

not sure if I am correct but mapproxy cannot talk directly with g3w but instead with qgis server. Can I connect the suite to an external qgis server? what options do I have to integrate mapproxy into g3w?

**Comment by volterra79** [comment]
> Hi Guys, I want to know if you can help me to understand how this plugging works and how can I use it. I want to integrate the mapproxy configuration file. However I'm not sure if this is possible with g3wsuite.
> 
> not sure if I am correct but mapproxy cannot talk directly with g3w but instead with qgis server. Can I connect the suite to an external qgis server? what options do I have to integrate mapproxy into g3w?

@wlorenzetti can you reply? Thanks

**Comment by Daparrag** [comment]
any update in this topic?

**Comment by wlorenzetti** [comment]
Hi @Daparrag we have a private module to use Mapproxy with G3W-SUITE, it replaces the core caching G3W-ADMIN module, for every layer of a project is possible get it on map by a WMTS service from mapproxy instance. If you are interested we can make a call and speak about it, for a custom service by our :)

**Comment by Daparrag** [comment]
@wlorenzetti  Sounds good. 
please let me know what time fits you well. would we possible today evening Europe time UTC/GMT +1 hour  ?

**Comment by Daparrag** [comment]
I write you on **_info@gis3w.it_** but not answer so far. 
would you please confirm this is a valid contact email?

**Comment by wlorenzetti** [comment]
> I write you on **_[info@gis3w.it](mailto:info@gis3w.it)_** but not answer so far. would you please confirm this is a valid contact email?

Sure is correct and email is arrived, @moovida reply to your email, don't you receive it?

**Comment by Daparrag** [comment]
unfortunately I did not receive your email. 
please verify my email-address: guzman.diego.at@gmail.com

**Pull request merged**
